### ISSUE TITLE
README and HOWTO for contribution

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/blog#101]
As discuss in the #96.

**Comment by samperochkin** [comment]
update : le post howto-fr est almost done. Après je clean les deux .md et on close ça.

**Comment by samperochkin** [comment]
Reste juste à passer vite fait sur le howto je pense. Le readme est comme le about du site (anlgais). J'ai juste ajouté un lien vers le site pour la version francaise.

**Comment by davebulaval** [comment]
Je pense que cette issue est close ?
