### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by stecaron** [dot-layer/blog#11]
Create the set up to link our site to a Google Analytics account to monitor the traffic on the site.

**Comment by chblw** [comment]
I'll look into this. For Google Analytics, we need an email address. I set up a temporary one at dotlayerorg@gmail.com and opened [community-tasks#12](https://github.com/dot-layer/community-tasks/issues/12) sor a permanent solution.

**Comment by stecaron** [comment]
Are there any costs for linking our site with a Google Analytics account?

**Comment by chblw** [comment]
No fees for Google Analytics. Then, it integrates simply with Adsense also.

**Comment by stecaron** [comment]
@chblw je pensais tu restais dans Montcalm et non Rockwood? ...

![image](https://user-images.githubusercontent.com/29443824/46556468-bf108700-c8b4-11e8-9d04-adcdd2f10f08.png)

**Comment by chblw** [comment]
On a déjà un fan!
