### ISSUE TITLE
Ajout dans how to

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/blog#111]
Ajouter lien vers nous contacter pour proposer un article.
Se linker sur le email.

**Comment by AnnieDeshaies** [comment]
En fait, on peut faire un nouveau formulaire qui link au email avec les requis necessaires pour l'entete des articles. Je pense ca serait plus simple pour les gens.

**Comment by AnnieDeshaies** [comment]
WIP

![image](https://user-images.githubusercontent.com/24190818/86537693-10e9a500-bebf-11ea-80a4-e281c8feda12.png)

Je l'ai essaye dans la page Contact.

![image](https://user-images.githubusercontent.com/24190818/86537714-2f4fa080-bebf-11ea-8dc7-830b4a3a18b8.png)

**Comment by davebulaval** [comment]
pt pas de within a day haha

**Comment by AnnieDeshaies** [comment]
Haha mais sinon on a un form pour les articles. Je sais pas quoi ecrire comme title pis toute mais si on veut le rajouter, reste pas grand chose a faire.

**Comment by AnnieDeshaies** [comment]
Ajouter un lien vers l'article pour expliquer comment contribuer en version Git
