### ISSUE TITLE
Soumission d'un article - adresse courriel

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/blog#130]
Si  je comprends bien, quelqu'un qui veut soumettre un article doit écrire SON adresse courriel dans la boîte "Adresse courriel du destinataire". Le texte dans la boîte me semble un peu confondant. Je propose qu'on y aille pour quelque chose du genre "Votre adresse courriel".

Des objections\clarifications? Ai-je bien compris?

**Comment by samperochkin** [comment]
![courriel-dl](https://user-images.githubusercontent.com/25728471/89313441-7d82cb80-d646-11ea-91bb-ca90c4d322a8.png)

**Comment by davebulaval** [comment]
Je seconde
