### ISSUE TITLE
Twitter refs not fully displayed

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/blog#17]
Sur mobile tout est beau, mais sur mon pc j'obtiens:
![sniptwit](https://user-images.githubusercontent.com/25728471/46576639-cf9c2c80-c99c-11e8-92f5-a56307c7fd3b.PNG)

**Comment by chblw** [comment]
Moi ça fonctionne sur Chrome

![image](https://user-images.githubusercontent.com/33635178/46576738-8c8f8880-c99f-11e8-91b1-c55d530e34e8.png)

**Comment by stecaron** [comment]
Chrome works well for me ! Safari works fine as well !

**Comment by caronl** [comment]
@samperochkin 
Dans mon cas, 2 trucs peuvent empêcher les références Twitter d'apparaître :  
1. Une extension de Chrome (Disconnect) bloque les trackers, dont Twitter. Si je Whitelist le site, ça fonctionne.
2. Une fois whitlisté, si je n'attends pas que tout le contenu de la page soit généré (la scroll bar continue de rapetisser même si l'animation de loading de Chrome a terminé) avant de scroll down, on dirait que Twitter reste dans ce mode là plus léger.

Ça dit quoi de ton côté?

**Comment by AntoineButeau** [comment]
@samperochkin ca le fait aussi de mon côté a cause de mon adblocker sur Chrome.
C'est un good to know, mais y'a rien a faire avec ça, donc je closerais le issue.
