### ISSUE TITLE
Setting a better RSS 

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/blog#20]
The RSS flux can be a easy way to make sur our reader came back to our blog. For now the setting is fine but we should set it to look more professional.

Plus we should consider remove the flickr icon.

**Comment by AntoineButeau** [comment]
Hey @davebulaval where do you see the Flickr icon?
I added the RSS icon in a branch called task/rss so now it appears at the top and bottom.

Also re: more professional - what do you have in mind? I have usually seen the RSS with the default style and people subscribing with their RSS/feed manager of choice (ie Feedly).

Other option would be to put the RSS feed on Feedburner similar to http://feeds.feedburner.com/avc

**Comment by davebulaval** [comment]
Legit for the RSS position. I'm not quite sure what I meant with more professional.

For the flickr I would remove it. Don't think is a nice tools for us.

**Comment by AntoineButeau** [comment]
Perfect. I don't see the flickr icon, can you send a screenshot?

Antoine Buteau

Engagement Manager
581-997-3658 ( tel:+15819973658 ) | LinkedIn ( https://www.linkedin.com/in/antoinebuteau/ )

**Comment by davebulaval** [comment]
I think it have been remove.

**Comment by AntoineButeau** [comment]
Sounds good.

Antoine Buteau

Engagement Manager
581-997-3658 ( tel:+15819973658 ) | LinkedIn ( https://www.linkedin.com/in/antoinebuteau/ )

**Comment by samperochkin** [comment]
I removed it (a long time ago) yeah.

**Comment by AntoineButeau** [comment]
Ok thanks, added RSS in PR #51
