### ISSUE TITLE
Uncategorized tag

### ISSUE THREAD

**Issue by chblw** [dot-layer/blog#21]
I saw someone already spotted this issue, but can't find it. There is an uncategorized tag : 
![screenshot from 2018-10-16 18-54-31](https://user-images.githubusercontent.com/33635178/47052144-2eb82900-d175-11e8-8a3a-bfab1b97b281.png)
Removing the blog/content/itemized directory solved this and doesn't seem to break anything.

**Comment by chblw** [comment]
It seems to be a past option from the example site

**Comment by stecaron** [comment]
Do you know how to fix that @chblw ?

**Comment by chblw** [comment]
I think so, I'll open a PR soon

**Comment by chblw** [comment]
#22 fixes this
