### ISSUE TITLE
Setting better community profile

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/blog#27]
Should we define a Code of conduct ?
A License ?

**Comment by davebulaval** [comment]
We should start a discuss which license we would like to take.

**Comment by davebulaval** [comment]
Yes for the about question.

**Comment by AnnieDeshaies** [comment]
Je pense que le about dans la page "about" devrait avoir un texte plus elabore que celui dans le sidebar. Est-ce qu'on veut ajouter la liste des membres qui ont startes dotlayer et peut-etre un code de conduite pour les commentaires et le code review?

**Comment by davebulaval** [comment]
About avec les membres fondateurs est intéressant. Le code de conduite aussi mais pas le code review sur le site par contre. Sur le repo oui définitivement.

**Comment by samperochkin** [comment]
J'aime l'idée des "membres fondateurs", mais j'ai peur que ça fasse un peu "groupe sélecte". Que diriez-vous plutôt d'expliquer le processus qui a mené à la fondation, en particulier l'idée derrière le premier chalet .Layer (dans le temps qu'on avait pas de nom!). J'ai un petit résumé quelque part.

**Comment by chblw** [comment]
Oui vous aviez présenté ça le premier soir du chalet v2. 

On pourrait faire un blogpost et linker à ce post dans le about.

**Comment by AnnieDeshaies** [comment]
C'est nice 👌 ou juste un blog post permanent dans la page "about"?

**Comment by samperochkin** [comment]
Personnellement, j'aime bien l'idée d'un texte permanent (plus long que dans le side panel) dans le About.

**Comment by davebulaval** [comment]
Je suis 100% d'accord avec ton commentaire Peroch (@samperochkin). Et j'aime l'idée de @chblw.

**Comment by samperochkin** [comment]
Je m'occupe du texte et quand c'est prêt je vous fais signe.

**Comment by davebulaval** [comment]
done
