### ISSUE TITLE
Sharing link won't show picture on LinkedIn

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/blog#44]
I have shared from the blog a LinkedIn post but the preview image won't show.

**Comment by davebulaval** [comment]
Documentation I found 
https://www.linkedin.com/help/linkedin/answer/46687

**Comment by caronl** [comment]
I should try submitting a fix tonight.

For future reference, we can add other cool and useful functionalities like that : https://gist.github.com/vietlq/d1c7ecfb20ce7beac4a7f4df746c797c

**Comment by davebulaval** [comment]
PR #47 for a partial correction.

**Comment by AnnieDeshaies** [comment]
All fixed, we can close this issue.
