### ISSUE TITLE
Update README tutorial to create a post

### ISSUE THREAD

**Issue by stecaron** [dot-layer/blog#52]
Update the tutorial to account for the modifications we made regarding multilingual site.

**Comment by stecaron** [comment]
@AntoineButeau @samperochkin @caronl can you take a quick look at the README of `task/translate-site` branch to see if my updates make sense. I updated it in order to work with the both english/french website.

**Comment by AntoineButeau** [comment]
Good for me. Would you need to translate the readme in french ^^ (trolling, no need)

**Comment by samperochkin** [comment]
Same, j'ai fait des modifs mineures.

**Comment by davebulaval** [comment]
It's this issue is still valid ?

**Comment by AnnieDeshaies** [comment]
Peut-être qu'on pourrait proposer aux gens de soit soumettre un article par le contact page pis par le git? Je sais pas si toute puller le projet pis faire all the things, ça bloque des gens? Je propose d'écrire un article là-dessus? Peut-être qu'on devrait avoir un FAQ... ?

**Comment by davebulaval** [comment]
Je suis d'accord. Ou un formulaire: soumettre un article et ça prefill un fichier .md qu'on pourrait ensuite à l'interne envoyer sur le site. 

Un article sur le blog ?

Oui pour le FAQ.

**Comment by davebulaval** [comment]
#101
