### ISSUE TITLE
Template for contributing to the blog.

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/blog#56]
J'ai créé un repo basic-post avec plus d'indications. Je vais essayer de faire ça en parallèle avec le tutoriel de Steph.

**Comment by samperochkin** [comment]
J'ai effacé le repo. Je me suis dit qu'avec le tutoriel c'est assez(?) Comme template, le futur auteur n'a qu'à partir d'un article existant. @stecaron, que dis-tu d'ajouter au tutoriel un lien vers un .md qui est sharp avec une petite phrase qui l'identifie comme un bon template? Same avec un .Rmd.

**Comment by samperochkin** [comment]
Je voulais dire: un lien vers des articles existants qui sont de bons exemples, i.e. des bons template si tu remove le body. Un bon exemple devrait donc avoir tous les caractéristiques que tu as listées.

**Comment by stecaron** [comment]
Ahhh okok ! Ouais ca pourrait effectivement faire la job !

**Comment by guillaume-chevalier** [comment]
@chblw Je suggèrerais d'ajouter des indications sur le ton des articles, ça semble important pour votre vision du blog. Aussi, une section quoi faire et quoi ne pas faire. 

Voici une citation de la première phrase du README.md: 

> The objective behind the blog is to make it easy for the community members (and anybody else) to promote their work and share their thoughts and ideas related to the field of data science/machine learning. 

Il serait bien de clarifier autour de ça. 

CC: @davebulaval @AnnieDeshaies 

P.S.: Désolé david pour le malentendu dans le premier commentaire de ma PR #67. Je parlais bien de Neuraxle et non de Neuraxio dans l'article - il s'agit très bien d'un projet et non pas d'une compagnie, je drois que j'avais saisi l'objectif du blog. Si tu CTRL+F pour `Neuraxio` dans [cette page du CI/CD](https://deploy-preview-67--relaxed-kepler-4b9238.netlify.com/blog/2019-10-26-neat-machine-learning-pipelines/neat-machine-learning-pipelines/), on voit bel et bien que dans mes commits originaux, Neuraxio est mentionné 1 seule fois, et la phrase n'est pas de la promotion. Cela dit, je vais enlever cette seule référence à Neuraxio. J'imagine que tu vas enlever ton "requested changes" après ça. 

P.S. @davebulaval tu pourrais probablement faire des blog posts pour chaque podcast, ou sinon en aggréger à coup de 3 podcasts par post pour faire des genre d'éditions des releases des podcasts? Idk, je lance l'idée. :smile:

**Comment by davebulaval** [comment]
Définitivement il faut ajouter cela. 

> P.S. @davebulaval tu pourrais probablement faire des blog posts pour chaque podcast, ou sinon en aggréger à coup de 3 podcasts par post pour faire des genre d'éditions des releases des podcasts? Idk, je lance l'idée.

J'ai déjà travailler sur cette idée ;) À suivre.

**Comment by davebulaval** [comment]
Still accurate ?

**Comment by AnnieDeshaies** [comment]
C'est pas mal la meme issue que la #101

**Comment by davebulaval** [comment]
Duplicate.
