### ISSUE TITLE
Poster les posts - comment?

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/blog#60]
On a l'heureux problème d'avoir (almost) deux posts à publier. Est-ce qu'on a une stratégie de postage? 

- intervals entre les posts
- jour de la semaine
- heure de la journée
- etc

**Comment by caronl** [comment]
Mon humble opinion :
- Intervalle : une semaine
- Jours de la semaine + heure de la journée : je sais qu'il y a plein d'écoles de pensées à ce sujet. Selon le réseau social sur lequel on veut faire de la pub ça varie aussi, mais vu que notre public cible c'est du monde qui lisent ça bien relax la fin de semaine, j'aurais tendance à dire entre vendredi midi et dimanche midi

**Comment by stecaron** [comment]
J'ai deja parler avec @jtbai et on a convenu qu'il allait poster le sien le 21 janvier je crois.

Pour ce qui est de la strategie en générale, je crois qu'une semaine pour le moment c'est un bon interval. On pourra s'ajuster en temps et lieu. Pour l'heure et le jour de la semaine je sais pas si je mettrais une condition. C'est plus sur les réseaux sociaux que c'est sensible. Je pense qu'on peut merger nos PR a peu pres n'importe quand, mais prendre le temps de les partager sur les reseaux sociaux a des moments précis (anyways comme @caronl dit, c'est clairement variable selon le médium).

**Comment by chblw** [comment]
Ce dashboard de Google Analytics pourrait éclaircir notre choix

![image](https://user-images.githubusercontent.com/33635178/50864007-ab226880-136e-11e9-80fc-7881fed3766d.png)

**Comment by caronl** [comment]
@chblw est-ce qu'on peut raccourcir le range jusqu'au dernier post? Sinon c'est un peu trop biaisé par les moments où on a fait notre pub sur les réseaux sociaux. Je sais que ya Noël là-dedans et que ça introduit un autre biais, mais quand même ya peut-être des trouvailles intéressantes à faire en testant les différents ranges qu'on a. 

Google Analytics serait aussi intéressant pour nous dire d'où viennent principalement les clics, donc à quelle plateforme on doit rester sensible (et quelle a besoin d'amour)

**Comment by chblw** [comment]
Sur une semaine (morte parce qu'il n'y a pas eu de post) c'est principalement la fin de semaine en pm. 

![image](https://user-images.githubusercontent.com/33635178/50864486-2e908980-1370-11e9-8ebb-ad0d19cf646a.png)

Nos referrals sont majoitairement de Facebook : 
![image](https://user-images.githubusercontent.com/33635178/50864566-6dbeda80-1370-11e9-9d10-d4466a63a6b6.png)

**Comment by jtbai** [comment]
donc @stecaron je pense que le 18 janvier sounds better avec cette histoire du vendredi!

**Comment by samperochkin** [comment]
Hier @stecaron @davebulaval et moi nous sommes dit que ce serait bien de merge juste un post par semaine, question de laisser leur heure de gloire à chaque post. Finalement, le mien on va p-ê attendre d'avoir une traduction avant de le promote, donc on pourrait faire une exception et merge celui de @jtbai quand même..

Mais pour l'avenir, on pourrait (informellement) se réserver la semaine qui nous convient quand on a un post en PR. Makes sense?

**Comment by davebulaval** [comment]
Il faudrais aussi retirer nos IP address pour ne pas fucker nos données.

**Comment by jtbai** [comment]
@samperochkin ahhh ouin tu te gate la traduction. Je vais peut être faire la meme chose de mon bord then. Mais disons que vendredi prochain pour moi ca serait bon pour mes deux version (anglais francais)

**Comment by jtbai** [comment]
@samperochkin  je ne savais pas que tu allais traduire. Je vais faire la meme chose though.
Je pense quand meme être bon pour release l'article la semaine prochaine (vendredi)

**Comment by davebulaval** [comment]
On va surement valider aussi avec un traducteur. L'idée étant qu'on veut utiliser meetupMLQC pour share les posts et envoyé vers la nouvelle page facebook de .Layer.. si nos premiers posts sont tous en anglais on va perdre des gens assez rapidement.

**Comment by davebulaval** [comment]
Is this issue still valid ?

**Comment by AnnieDeshaies** [comment]
Je pense qu'on peut closer cet issue là @samperochkin ?

**Comment by samperochkin** [comment]
Ouep!
