### ISSUE TITLE
Logo .Layer absent de la home page

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/blog#69]
Faudrait penser à insérer le logo somewhere in there hen.

**Comment by AnnieDeshaies** [comment]
Vous voulez le mettre ou? Dans le menu ou avec le .Layer du titre? Ou les deux?

**Comment by AnnieDeshaies** [comment]
Voir PR #70  :)

![image](https://user-images.githubusercontent.com/24190818/68151543-e9959f00-ff0f-11e9-9919-d84dce4b0e3f.png)
![image](https://user-images.githubusercontent.com/24190818/68151554-ebf7f900-ff0f-11e9-9aa9-c25ac5f756f8.png)

**Comment by samperochkin** [comment]
Ça look. Mais il apparait pas en fr. T'as une idée pourquoi?

**Comment by AnnieDeshaies** [comment]
J'ai oublie de le rajouter dans version en francais... jai fait ca en ecoutant des videos de formation a ma job, mauvaise idee 😑 ca me fait faire des Pr a moitie fonctionnelle 😓

**Comment by AnnieDeshaies** [comment]
Should be fixed now 👌👌👌

**Comment by davebulaval** [comment]
Good ?
