### ISSUE TITLE
Implement Sass

### ISSUE THREAD

**Issue by AnnieDeshaies** [dot-layer/blog#71]
Je pense qu'on devrait utiliser SASS au lieu d'une feuille CSS pour les styles _custom_. Ça se lit mieux et ça évite la répétition de code. Si on veut changer des choses dans le _template_, vaudrait mieux _setup_ la feuille de style tout de suite plutôt que d'attendre plus tard... je pense?

**Comment by davebulaval** [comment]
Aucune idée c'est quoi, mais les arguments qui le jsutifie me semblent valable.

**Comment by AnnieDeshaies** [comment]
Hahaha je viens d'essayer de quoi, mais netlify me bloque. Je vais continuer à regarder ça plus tard. Closed Pr for now haha

**Comment by AnnieDeshaies** [comment]
Je close cet issue là. Pas une priorité pis en plus je peux en masse juste cleaner le CSS qu'on a déjà à la place. On repensera à ça un jour si on a rien d'autre à faire.
