### ISSUE TITLE
RSS flux

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/blog#79]
The RSS don't seem to work.

![image](https://user-images.githubusercontent.com/24845694/68548687-a62eab00-03bd-11ea-99cc-e1af8f892b93.png)

![image](https://user-images.githubusercontent.com/24845694/68548697-b47cc700-03bd-11ea-8d98-d0ee09022c2b.png)

**Comment by guillaume-chevalier** [comment]
RSS is important

**Comment by AnnieDeshaies** [comment]
Est-ce que le rss a dja fonctionne?

**Comment by davebulaval** [comment]
Je ne pense pas.

**Comment by AnnieDeshaies** [comment]
Je vais regarder aujourd'hui apres avoir fixe ma PR. 👌

**Comment by AnnieDeshaies** [comment]
Le Rss fonctionnait. Je l'ai remis (en PR en ce moment) avec certaines modifs. 
Sadly on roule sur une vieille version de Go, je vais tchecker comment l'entente du xml etait ecrit a la base. Je me suis base sur une version recente.
