### ISSUE TITLE
Update contact page look

### ISSUE THREAD

**Issue by AnnieDeshaies** [dot-layer/blog#80]
Je pense que le contact form manque de spacing et je mettrais juste 'Name' au lieu de 'Your name' dans les placeholders. Celui pour le sujet du mail à rien d'écrit dedans, faut corriger ça!

Je vais essayer de respecter les espacements comme ils sont partout dans le site pour voir qu'est-ce que ça donne.

![image](https://user-images.githubusercontent.com/24190818/68694486-3fd59400-0547-11ea-8207-8bbb1fe6426f.png)

**Comment by AnnieDeshaies** [comment]
Vous pensez quoi de changer le titre pour "Get in touch"

**Comment by AnnieDeshaies** [comment]
On parle pas le meme francais haha

![image](https://user-images.githubusercontent.com/24190818/68695361-e2424700-0548-11ea-8611-7c1980479921.png)

**Comment by AnnieDeshaies** [comment]
Les messages s'envoie la --> emailservice = "formspree.io/example@email.com" 
Pas sure que c'est une adresse valide... On as-tu un email @davebulaval @stecaron ?

**Comment by davebulaval** [comment]
> Vous pensez quoi de changer le titre pour "Get in touch"

Vraiment plus conviviale.

**Comment by davebulaval** [comment]
> Les messages s'envoie la --> emailservice = "formspree.io/example@email.com"
> Pas sure que c'est une adresse valide... On as-tu un email @davebulaval @stecaron ?

Je suis jamais sur du nom. @stecaron
