### ISSUE TITLE
Dates bilingues

### ISSUE THREAD

**Issue by chblw** [dot-layer/blog#83]
Ce problème a été soulevé dans #63, où les dates en français apparaîtront toutes comme janiver. 

Le janvier vient du hard code dans la config date_format [fr.toml](https://github.com/dot-layer/blog/blob/master/i18n/fr.toml) car January est une variable et Janvier est un string. 

Hugo n'offre pas de support bilingue mais en parle [ici](https://gohugo.io/content-management/multilingual/#customize-dates)

La solution présentée [ici](https://discourse.gohugo.io/t/dates-only-in-english/1317/40) semble la plus simple vu qu'on a déjà un fr.toml, mais mes skills de html sont trop noob pour faire ça.

**Comment by stecaron** [comment]
@AntoineButeau any idea?

**Comment by AnnieDeshaies** [comment]
Oh I see! Clairement juste la fonction de format de date. Je suis passee a cote en jouant dans les posts de book review. Suffit de la refaire pour les .fr avec une condition a savoir si le site en en francais ou en anglais. No problemo. Je prends mon ordi pis je vous fait ca. 🤙

**Comment by AnnieDeshaies** [comment]
Fixed w/ PR #88 （＾ｖ＾）
