### ISSUE TITLE
Copyright update ?

### ISSUE THREAD

**Issue by chblw** [dot-layer/blog#91]
Le site a été mis à jour aujourd'hui mais l'année du copyright n'a pas été mis à jour. À vérifier quand le post de steph sera merged.

https://github.com/dot-layer/blog/blob/b289089019b4233cf43a9572902093aaf2b37405/layouts/partials/sidebar.html#L142

**Comment by AnnieDeshaies** [comment]
Le site va se mettre a jour avec le prochain article! Ca prend l'année du dernier article et ça le met à jour :) J'ai vérifié tantôt :)
