### ISSUE TITLE
index en EN ou FR

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/blog#93]
@davebulaval a soulevé ce point dans #89 . Je pense que la question vaut la peine qu'on s'y attarde. EN c'est plus accessible en général, mais compte tenu de notre auditoire peut-être que FR serait plus logique.

**Comment by davebulaval** [comment]
Actuellement, notre clientèle me semble plus FR de par les activités de Meetup, OpenLayer et le chalet. Cela me semble plus pertinent. Sauf, qu'il faudrait dire qu'il n'y a pas les mêmes articles nécessairement dans les deux langues.

**Comment by AnnieDeshaies** [comment]
Bon point, on les traduit tu toute? Je suis down pour en faire un de temps en temps.

**Comment by davebulaval** [comment]
> Bon point, on les traduit tu toute? Je suis down pour en faire un de temps en temps.

Si tu est motivée, why not.. mais, je trouve que tu en fais déjà beaucoup alors on (le comité blog) pourrait regarder avec la communauté .Layer pour trouver 2-3 autres personnes pour le faire?

**Comment by samperochkin** [comment]
Je suis d'accord avec Dave. Même que, à mon avis, ce ne serait pas nécessairement une bonne chose de les traduire. Les articles en français vise généralement (quasi uniquement) un publique francophone. Si un auteur veut les deux langues, je pense que c'est à lui/elle de traduire.

**Comment by AnnieDeshaies** [comment]
Aight! 🤗

**Comment by AnnieDeshaies** [comment]
On fait un vote? Le president disait que anglais a l'air plus accessible, David dit Fr, je dis loi 101 pis Sam tu dis Fr serait plus logique peut-etre?

**Comment by samperochkin** [comment]
Ouais un vote serait bien. Je pense que le point sur lequel il faudrait focaliser sur comment les gens accèdent au site. Ceux et celles qui accèdent au site via un lien d'article arrivent nécessairement dans la bonne langue. La vraie question, à mon avis, est :

- Ceux et celles qui accèdent au site par la homepage/page d'accueil sont majoritairement anglophones ou francophones? (Et si c'est sur ça qu'on veut se fier, of course.)

**Comment by samperochkin** [comment]
Je transfert sur slack et j'écrirai ici le résultat du vote.

**Comment by samperochkin** [comment]
Pas de doute. Tout le monde s'entend pour FR. @AnnieDeshaies, on a une to-do-list qqpart?

**Comment by AnnieDeshaies** [comment]
@samperochkin J'ecrivais mes trucs a faire dans issue #86, je peux changer ca en meme temps que ma PR pour retirer le plugin de commentaires. Je vais linker les deux issues ensemble

**Comment by AnnieDeshaies** [comment]
Update: Je ne peux pas acceder au langage du browser de l'utilisateur avec un generateur de site static. Je pourrais p-e faire un script javascript, mais pas a soir haha

**Comment by AnnieDeshaies** [comment]
En attendant, on peut le mettre en francais pis faite poper un message qui dit "eille allez voir mes textes en anglais y too, much selection, autres articles, very auteurs de feu"

**Comment by samperochkin** [comment]
Pas de trouble! C'est pas pressant non plus. Juste le mettre en FR c'est déjà bien fo-now.

**Comment by AnnieDeshaies** [comment]
je vais faire ca 2d 🤙

**Comment by AnnieDeshaies** [comment]
Pas eu l'energie, j'ai la pire grippe de ma vie. Je me mets un reminder de corriger en meme temps le page precendente et page suivante --> en mobile fr, je le vois pas et ca affiche juste 5 articles. Faudrait je check en desktop.

**Comment by davebulaval** [comment]
#105 done.
