### ISSUE TITLE
On garde les commentaires?

### ISSUE THREAD

**Issue by AnnieDeshaies** [dot-layer/blog#94]
Le plugins de commentaires Disqus essaie de spammer le browser avec des ad malwares qui trackent les préférences des utilisateurs pour envoyer de la pub. Bon, c'est pas trop grave, mais ça ralentit le loading speed du site pis personne écrit des commentaires en plus... 

Bref, on enlève ti le plugin de commentaires? C'est le même que dans wordpress, ça me trigger... Wordpress me trigger... J'aime pas PHP.... Bref, opinions? Commentaires?

![image](https://user-images.githubusercontent.com/24190818/71773265-49b4bb80-2f28-11ea-8bcf-dec14dd86069.png)

**Comment by davebulaval** [comment]
Selon moi, inutile.

**Comment by AnnieDeshaies** [comment]
Perso, j'aurais plus tendance a ecrire un commentaire sur facebook plus que sur le blog... ¯\_(ツ)_/¯ Diqus est un peu vieux looking pas fiable a se linker dessus d'un point de vue utilisateur... Je sais pu si c'est relevant de mettre des commentaires dans un blog.

**Comment by samperochkin** [comment]
Same same. Useless (pour l'instant du moins) je pense.

**Comment by stecaron** [comment]
Ben d'accord aussi ! Pas comme si on allait avoir des grosses discussions sur Disqus à court terme haha !

**Comment by AnnieDeshaies** [comment]
Let's burn it all with fire!!! Je vais attendre de voir si on a d'autres opinions sinon vendredi j'ouvre une PR pis byebye disqus! Ca va m'enlever pas mal d'erreurs de console de browser a tchecke pour ma checklist de maintenance du site 👌

**Comment by AnnieDeshaies** [comment]
DO --> index en EN ou FR #93 
a.k.a Fr par defaut, sinon browser location?

**Comment by samperochkin** [comment]
Ouep. Je me trompe ou c'était bien ça?
