### ISSUE TITLE
Add CC-BY license?

### ISSUE THREAD

**Issue by guillaume-chevalier** [dot-layer/blog#96]
For all future posts of contributors. 

And for past posts: whoever accepts (code review approve) the eventual license PR will mean that they allow their existing past posts (that are not yet under this license) to be under this license as if the license was already set on their articles before. 

Info: https://creativecommons.org/licenses/by/4.0/

**Comment by guillaume-chevalier** [comment]
Related: PR #95's review comment of @davebulaval and @chblw about reposting.

**Comment by davebulaval** [comment]
Good point.

**Comment by davebulaval** [comment]
Meaning we allow to have two identical (or near) article on two different platform ?

**Comment by AnnieDeshaies** [comment]
Comme le readme de yolo dit:



![20200105_210845](https://user-images.githubusercontent.com/24190818/71790676-ae8f1500-2fff-11ea-93b6-eebff07c30d7.jpg)

**Comment by AnnieDeshaies** [comment]
Mais personnellement oui je vois pas pourquoi on n'encouragerait pas le partage d'informations.

**Comment by guillaume-chevalier** [comment]
> Meaning we allow to have two identical (or near) article on two different platform ?

En gros, avec CC-BY si le monde copient quelque chose qui vient de ce que l'auteur a fait, eh bien celui qui copie doit citer l'auteur, le plus souvent avec une URL je crois. Donc ça permet tout contenu dérivé sous condition de citation en gros. 

Par exemple, perso je partage mes figures de ML sous CC-BY: https://github.com/guillaume-chevalier/Machine-Learning-Figures

**Comment by guillaume-chevalier** [comment]
Précision sur mon commentaire précédent... quand je dis ça:
> En gros, avec CC-BY si le monde copient quelque chose qui vient de ce que l'auteur a fait, eh bien celui qui copie doit citer l'auteur, le plus souvent avec une URL je crois. Donc ça permet tout contenu dérivé sous condition de citation en gros.

En fait pour être clair, ça permettrait de faire du contenu dérivé *depuis* le blog *vers* d'autres endroits, mais ça n'indique rien pour le sens inverse. Donc si quelqu'un utilise du contenu qui vient de d'autres endroits pour le mettre ici, il doit s'assurer que c'est correct, naturellement. Ainsi, pour ce qui en est de reposter des articles qui viennent d'ailleurs, il faut donc que ça soit fait correctement quand même (e.x.: avoir permission de l'auteur somehow, tel que s'il ouvre lui-même la PR de repost de son article, ou si son article est déjà disponible sous une license qui le permet).

**Comment by davebulaval** [comment]
> Précision sur mon commentaire précédent... quand je dis ça:
> 
> > En gros, avec CC-BY si le monde copient quelque chose qui vient de ce que l'auteur a fait, eh bien celui qui copie doit citer l'auteur, le plus souvent avec une URL je crois. Donc ça permet tout contenu dérivé sous condition de citation en gros.
> 
> En fait pour être clair, ça permettrait de faire du contenu dérivé _depuis_ le blog _vers_ d'autres endroits, mais ça n'indique rien pour le sens inverse. Donc si quelqu'un utilise du contenu qui vient de d'autres endroits pour le mettre ici, il doit s'assurer que c'est correct, naturellement. Ainsi, pour ce qui en est de reposter des articles qui viennent d'ailleurs, il faut donc que ça soit fait correctement quand même (e.x.: avoir permission de l'auteur somehow, tel que s'il ouvre lui-même la PR de repost de son article, ou si son article est déjà disponible sous une license qui le permet).

Je suis d'accord, il faudrait juste que notre README (qui devrait plutôt être un HOWTO ou CONTRIBUTING) inclue une mention de la licence pour le site ET une mention lorsque l'article a déjà été diffusé à l'externe.

**Comment by AnnieDeshaies** [comment]
J'aimerais ben m'occuper de refaire le README pour vrai. Je pensais uniformiser les metas des articles et ou mettre les images pis toute pis toute fake au fur et a mesure que je placerais le stock, jpourrais ecrire quoi faire pour faire un draft en git. Aussi, faut je teste le contactez-nous si on veut proposer de pouvoir envoyer un texte. Ca commencait avec enlever les erreurs dans la console, c'est en pr fake prochaine etape tester les formulaires pi les courriels.

**Comment by samperochkin** [comment]
Je pensais aussi me lancer là-dessus @AnnieDeshaies . Que penses-tu de mettre un file .md (et un .Rmd aussi) qui servirait de template pour contribuer. Les metas y seraient déjà tout bien initialisé avec des exemples (Jane Doe). Dans le README on fait une description très sommaire de comment faire et on pointe vers un article plus complet. Ça me ferait plaisir d'écrire une bonne ébauche de l'article et on pourrait le finaliser ensemble pour qu'il soit cohérent avec le README.

**Comment by AnnieDeshaies** [comment]
C'est mieux de meme, j'ai toujours envie d'ecrire des niaiseries quand j'ecris... A matin me suis levee avec "imma barbie gurl in a barbie world" pis ca ma fait penser que astheure tu pouvais acheter curvy barbie, tall barbie ou barbie handicapee. Sick!

**Comment by davebulaval** [comment]
> Que penses-tu de mettre un file .md (et un .Rmd aussi) qui servirait de template pour contribuer. 

J'aime l'idée du .Rmd.
